### ISSUE TITLE
All size | intro_img : Image & feedFailsafe_img : Image mismatch with ref

### ISSUE THREAD

**Issue by Shahnul-sebpo** [sebpo1/USCS_1437#15]
Duracell - SA:
Staples_CoOp_SA_Carousel_Duracell_XX_Duracell_Generic_112022

![1](https://user-images.githubusercontent.com/95062434/202347843-0744fcf7-4415-4452-a2b0-2ac9e13e57c8.png)

**Comment by saddam-sebpo** [comment]
Thank you. The file has been updated and basefile sent to QA

**Comment by fariha-sebpo** [comment]
Solved
