### ISSUE TITLE
All size | "logo_img : Image" mismatch with ref

### ISSUE THREAD

**Issue by Shahnul-sebpo** [sebpo1/USCS_1437#16]
TOPS:
Staples_CoOp_CD_Carousel_Tops_Adams_TaxForm_TaxSeasonPrep_112022
Staples_CoOp_ACQ_Carousel_Tops_Adams_TaxForm_TaxSeasonPrep_112022

![2](https://user-images.githubusercontent.com/95062434/202361345-c28f78ee-7679-4a58-998a-04e8c3aa2f2d.png)

**Comment by saddam-sebpo** [comment]
Thank you. The file has been updated and basefile sent to QA

**Comment by fariha-sebpo** [comment]
Solved
