### ISSUE TITLE
Basefile : Dotcom Avery | SKU value mismatched

### ISSUE THREAD

**Issue by susmita-sebpo** [sebpo1/USCS_1437#2]
![image](https://user-images.githubusercontent.com/100709063/181373748-d1a1945e-5da4-44da-a588-e662df8a8411.png)

![image](https://user-images.githubusercontent.com/100709063/181373548-78762336-aa9a-41b9-a899-14da1a4f45af.png)

**Comment by sakib-sebpo** [comment]
Fixed

**Comment by susmita-sebpo** [comment]
fixed

**Comment by susmita-sebpo** [comment]
closed
