### ISSUE TITLE
HP Inkjet | Envy_Photos_AT_home, GetReal_OJP, Great Ideas | Wrong SKU and Wrong price

### ISSUE THREAD

**Issue by mithila-sebpo** [sebpo1/USCS_1437#3]
![image](https://user-images.githubusercontent.com/95068780/181373501-8fd11672-3e7e-450b-8bfe-5cdb550c8d7e.png)
![image](https://user-images.githubusercontent.com/95068780/181373766-940ba708-c300-40e7-ac48-0936f574c227.png)

**Comment by sakib-sebpo** [comment]
Updated.

**Comment by mithila-sebpo** [comment]
**Not solved for GetReal_OJP and Great Ideas**
![image](https://user-images.githubusercontent.com/95068780/181389485-79f1a9b5-0846-4ba9-8312-1b827762af02.png)
![image](https://user-images.githubusercontent.com/95068780/181389497-eed073fc-7429-4af1-9097-9bc8dc44c1a9.png)


![image](https://user-images.githubusercontent.com/95068780/181389716-92de1c5c-1c6e-4d40-8400-44e88534b9ac.png)
![image](https://user-images.githubusercontent.com/95068780/181389726-ac84ffd0-3fd7-43c6-91a4-7156ae356d3f.png)

**Comment by mithila-sebpo** [comment]
solved
