### ISSUE TITLE
Intel Dotcom | Staples_CoOp_ACQ_Carousel_Intel_Intel-PCs_Core_PC-Sale1_082822 , Staples_CoOp_CD_Carousel_Intel_Intel-PCs_Core_PC-Sale1_082822 | Product 1 price mismatch

### ISSUE THREAD

**Issue by retuparna-sebpo** [sebpo1/USCS_1437#4]
**Version Name :** Staples_CoOp_ACQ_Carousel_Intel_Intel-PCs_Core_PC-Sale1_082822

![image](https://user-images.githubusercontent.com/106819920/186500476-5d751334-1207-4853-bc51-5d26171c1817.png)
![image](https://user-images.githubusercontent.com/106819920/186500857-5668be9d-1ed6-4b7f-b2ce-f90160090b9a.png)

**Version name**   : Staples_CoOp_CD_Carousel_Intel_Intel-PCs_Core_PC-Sale1_082822

![image](https://user-images.githubusercontent.com/106819920/186504932-7817c9f4-2cb2-4efd-9bf1-d4cf84a48fb8.png)

![image](https://user-images.githubusercontent.com/106819920/186504978-01f4846b-355b-499a-8942-6642121a0fdf.png)

**Comment by sakib-sebpo** [comment]
Solved

**Comment by retuparna-sebpo** [comment]
Fixed
