### ISSUE TITLE
size : all | HP InkJet, HP LaserJet | intro Image and feed Fail Image mismatch

### ISSUE THREAD

**Issue by mithila-sebpo** [sebpo1/USCS_1437#8]
Staples_CoOp_DotCom_Carousel_HP_Printers-Inkjet_XX_Product-Printer_100922
Staples_CoOp_DotCom_Carousel_HP_Printers-Laserjet_XX_Product-Printer_100922

![image](https://user-images.githubusercontent.com/95068780/194143289-5b71fe7b-af92-4801-a77d-e6364ef0c3f3.png)
![image](https://user-images.githubusercontent.com/95068780/194145135-9a71f929-0c16-4404-a72f-74babee95613.png)

**Comment by sakib-sebpo** [comment]
Fixed

**Comment by mithila-sebpo** [comment]
solved
